services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer                       
    ports:
      - "1433:1433"
    networks:
      - emarket

  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks: 
      - emarket
  
  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq-broker
    ports:
        - "5672:5672"
        - "15672:15672"
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
    networks: 
      - emarket

  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    depends_on: 
      - mssql
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EMarket_Identity_Db;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
    networks:
      - emarket

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    ports:
      - "5001:8080"
    depends_on: 
      - mssql
      - rabbitmq
    environment:
      - ConnectionStrings__DefaultConnection=Server=mssql;Database=EMarket_Catalog_Db;User Id=sa;Password=${DB_PASSWORD};TrustServerCertificate=True;
      - RabbitMQ__Host=rabbitmq
    networks: 
      - emarket

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    ports:
      - "5002:8080"
    depends_on: 
      - redis
      - rabbitmq
    environment:
      - RabbitMQ__Host=rabbitmq
      - Redis__ConnectionString=redis:6379
    networks: 
      - emarket

  emarket.gateway:
    image: ${DOCKER_REGISTRY-}emarketgateway
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: src/EMarket.Gateway/Dockerfile
    depends_on:
      - identity.api
      - catalog.api
      - cart.api
    networks:
      - emarket
    
networks:
  emarket:
    driver: bridge

volumes:
  redis-data:
  rabbitmq-data: