services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_server
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=${DB_PASSWORD}
      - MSSQL_PID=Developer                       
    ports:
      - "1433:1433"
    networks:
      - emarket

  redis:
    image: redis:latest
    container_name: redisdb
    ports:
      - "6379:6379"
    networks: 
      - emarket
      
  identity.api:
    image: ${DOCKER_REGISTRY-}identityapi
    ports:
      - "5001:8080"
    build:
      context: .
      dockerfile: src/Identity.API/Dockerfile
    depends_on: 
      - mssql
    env_file:
      - .env
    networks: 
      - emarket

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    ports:
      - "5002:8080"
    build:
      context: .
      dockerfile: src/Catalog.API/Dockerfile
    depends_on: 
      - mssql
    env_file:
      - .env
    networks: 
      - emarket

  cart.api:
    image: ${DOCKER_REGISTRY-}cartapi
    ports:
      - "5003:8080"
    build:
      context: .
      dockerfile: src/Cart.API/Dockerfile
    depends_on: 
      - redis
    networks: 
      - emarket

  emarket.gateway:
    image: ${DOCKER_REGISTRY-}emarketgateway
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: src/EMarket.Gateway/Dockerfile
    depends_on:
      - identity.api
      - catalog.api
      - cart.api
    networks:
      - emarket
    

networks:
  emarket:
    driver: bridge
